### PR TITLE
Increase JSON batch size from 80 to 1024

### PR DESCRIPTION
**Pull request by joelkoen**
(or something smaller if you think that's better)

### CODE REVIEW

**Comment by zamojski** [comment]
What is that supposed to change for end user? On an older phone this may result in a very rarely updated progress bar. Also the PR doesn't cover all other file types.

**Comment by joelkoen** [comment]
This PR tries to decrease the amount of requests made when submitting to BeaconDB. This improves submission speed as the server can commit more writes in a single database transaction, and for users on high-latency connections this should make a big difference as the reduced amount of requests means there are less round trips while the client waits for a response.

I didn't consider older phones, happy to hear your thoughts on the performance impact this may have. 1024 is probably overkill anyway.

**Comment by zamojski** [comment]
Ok, in such case it's a wrong class :) It should be in `UploadWorker`.

However there I load measurements once for both OCID and MLS uploads in order to save memory and avoid different upload progress for each of projects. Probably it could be refactored and separated but for now it isn't the case.

One reason behind the existing value is the upload file size limitation in OCID (which I cannot predict until the data is serialized to CSV) I read only and upload 85 measurements (which may contain multiple cells and that varies the size of generated file).

**Comment by joelkoen** [comment]
Oops, you can probably tell Android/Java isn't my thing ;)

As this is a bit difficult to do without significant code changes, I'll open a new issue with some other ways forward to discuss.

**Pull request closed without merging**
