### PR TITLE
added feature graphic and screenshots for F-Droid app store via fastlane

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by zamojski** [comment]
How this content will be made available to F-Droid by just placing information in readme?
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by PanderMusubi** [comment]
If the `fastlane` directory is at top-level in the release, all will land automatically.

**Comment by zamojski** [comment]
As per #50 the file hierarchy is not correct. I will close this pull request without merging but thanks for putting my attention to this :)

**Comment by PanderMusubi** [comment]
But you will add the contributed graphics to fastlane?

**Comment by zamojski** [comment]
I will add the ones from #50 because screenshots are more up to date now (support for MLS is missing on yours).

**Pull request closed without merging**
